package com.pojos;
// Generated Sep 22, 2019 11:27:50 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AlumnoHasAsignacion generated by hbm2java
 */
public class AlumnoHasAsignacion  implements java.io.Serializable {


     private int idAlumAsig;
     private Asignacion asignacion;
     private Aula aula;
     private PerAlumno perAlumno;
     private Date fecAsig;

    public AlumnoHasAsignacion() {
    }

    public AlumnoHasAsignacion(int idAlumAsig, Asignacion asignacion, Aula aula, PerAlumno perAlumno, Date fecAsig) {
       this.idAlumAsig = idAlumAsig;
       this.asignacion = asignacion;
       this.aula = aula;
       this.perAlumno = perAlumno;
       this.fecAsig = fecAsig;
    }
   
    public int getIdAlumAsig() {
        return this.idAlumAsig;
    }
    
    public void setIdAlumAsig(int idAlumAsig) {
        this.idAlumAsig = idAlumAsig;
    }
    public Asignacion getAsignacion() {
        return this.asignacion;
    }
    
    public void setAsignacion(Asignacion asignacion) {
        this.asignacion = asignacion;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public PerAlumno getPerAlumno() {
        return this.perAlumno;
    }
    
    public void setPerAlumno(PerAlumno perAlumno) {
        this.perAlumno = perAlumno;
    }
    public Date getFecAsig() {
        return this.fecAsig;
    }
    
    public void setFecAsig(Date fecAsig) {
        this.fecAsig = fecAsig;
    }




}


