package com.pojos;
// Generated Sep 20, 2019 1:20:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignacion generated by hbm2java
 */
public class Asignacion  implements java.io.Serializable {


     private int idAsignacion;
     private Grado grado;
     private Nivel nivel;
     private Seccion seccion;
     private boolean flgDispoVacancia;
     private Set<AlumnoHasAsignacion> alumnoHasAsignacions = new HashSet<AlumnoHasAsignacion>(0);

    public Asignacion() {
    }

	
    public Asignacion(int idAsignacion, Grado grado, Nivel nivel, Seccion seccion, boolean flgDispoVacancia) {
        this.idAsignacion = idAsignacion;
        this.grado = grado;
        this.nivel = nivel;
        this.seccion = seccion;
        this.flgDispoVacancia = flgDispoVacancia;
    }
    public Asignacion(int idAsignacion, Grado grado, Nivel nivel, Seccion seccion, boolean flgDispoVacancia, Set<AlumnoHasAsignacion> alumnoHasAsignacions) {
       this.idAsignacion = idAsignacion;
       this.grado = grado;
       this.nivel = nivel;
       this.seccion = seccion;
       this.flgDispoVacancia = flgDispoVacancia;
       this.alumnoHasAsignacions = alumnoHasAsignacions;
    }
   
    public int getIdAsignacion() {
        return this.idAsignacion;
    }
    
    public void setIdAsignacion(int idAsignacion) {
        this.idAsignacion = idAsignacion;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Nivel getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Nivel nivel) {
        this.nivel = nivel;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }
    public boolean isFlgDispoVacancia() {
        return this.flgDispoVacancia;
    }
    
    public void setFlgDispoVacancia(boolean flgDispoVacancia) {
        this.flgDispoVacancia = flgDispoVacancia;
    }
    public Set<AlumnoHasAsignacion> getAlumnoHasAsignacions() {
        return this.alumnoHasAsignacions;
    }
    
    public void setAlumnoHasAsignacions(Set<AlumnoHasAsignacion> alumnoHasAsignacions) {
        this.alumnoHasAsignacions = alumnoHasAsignacions;
    }




}


