package com.pojos;
// Generated Sep 20, 2019 1:20:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aula generated by hbm2java
 */
public class Aula  implements java.io.Serializable {


     private int idAula;
     private EstadoAula estadoAula;
     private String nomAula;
     private int aforoAula;
     private Set<AlumnoHasAsignacion> alumnoHasAsignacions = new HashSet<AlumnoHasAsignacion>(0);

    public Aula() {
    }

	
    public Aula(int idAula, EstadoAula estadoAula, int aforoAula) {
        this.idAula = idAula;
        this.estadoAula = estadoAula;
        this.aforoAula = aforoAula;
    }
    public Aula(int idAula, EstadoAula estadoAula, String nomAula, int aforoAula, Set<AlumnoHasAsignacion> alumnoHasAsignacions) {
       this.idAula = idAula;
       this.estadoAula = estadoAula;
       this.nomAula = nomAula;
       this.aforoAula = aforoAula;
       this.alumnoHasAsignacions = alumnoHasAsignacions;
    }
   
    public int getIdAula() {
        return this.idAula;
    }
    
    public void setIdAula(int idAula) {
        this.idAula = idAula;
    }
    public EstadoAula getEstadoAula() {
        return this.estadoAula;
    }
    
    public void setEstadoAula(EstadoAula estadoAula) {
        this.estadoAula = estadoAula;
    }
    public String getNomAula() {
        return this.nomAula;
    }
    
    public void setNomAula(String nomAula) {
        this.nomAula = nomAula;
    }
    public int getAforoAula() {
        return this.aforoAula;
    }
    
    public void setAforoAula(int aforoAula) {
        this.aforoAula = aforoAula;
    }
    public Set<AlumnoHasAsignacion> getAlumnoHasAsignacions() {
        return this.alumnoHasAsignacions;
    }
    
    public void setAlumnoHasAsignacions(Set<AlumnoHasAsignacion> alumnoHasAsignacions) {
        this.alumnoHasAsignacions = alumnoHasAsignacions;
    }




}


