package com.pojos;
// Generated Sep 22, 2019 11:27:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Discapacidad generated by hbm2java
 */
public class Discapacidad  implements java.io.Serializable {


     private int idDiscapacidad;
     private String nomDiscapacidad;
     private Set<PerAlumno> perAlumnos = new HashSet<PerAlumno>(0);

    public Discapacidad() {
    }

	
    public Discapacidad(int idDiscapacidad) {
        this.idDiscapacidad = idDiscapacidad;
    }
    public Discapacidad(int idDiscapacidad, String nomDiscapacidad, Set<PerAlumno> perAlumnos) {
       this.idDiscapacidad = idDiscapacidad;
       this.nomDiscapacidad = nomDiscapacidad;
       this.perAlumnos = perAlumnos;
    }
   
    public int getIdDiscapacidad() {
        return this.idDiscapacidad;
    }
    
    public void setIdDiscapacidad(int idDiscapacidad) {
        this.idDiscapacidad = idDiscapacidad;
    }
    public String getNomDiscapacidad() {
        return this.nomDiscapacidad;
    }
    
    public void setNomDiscapacidad(String nomDiscapacidad) {
        this.nomDiscapacidad = nomDiscapacidad;
    }
    public Set<PerAlumno> getPerAlumnos() {
        return this.perAlumnos;
    }
    
    public void setPerAlumnos(Set<PerAlumno> perAlumnos) {
        this.perAlumnos = perAlumnos;
    }




}


