package com.pojos;
// Generated Sep 20, 2019 1:20:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Enfermedad generated by hbm2java
 */
public class Enfermedad  implements java.io.Serializable {


     private int idEnfermedad;
     private String nomEnfermedad;
     private Set<PerAlumno> perAlumnos = new HashSet<PerAlumno>(0);

    public Enfermedad() {
    }

	
    public Enfermedad(int idEnfermedad) {
        this.idEnfermedad = idEnfermedad;
    }
    public Enfermedad(int idEnfermedad, String nomEnfermedad, Set<PerAlumno> perAlumnos) {
       this.idEnfermedad = idEnfermedad;
       this.nomEnfermedad = nomEnfermedad;
       this.perAlumnos = perAlumnos;
    }
   
    public int getIdEnfermedad() {
        return this.idEnfermedad;
    }
    
    public void setIdEnfermedad(int idEnfermedad) {
        this.idEnfermedad = idEnfermedad;
    }
    public String getNomEnfermedad() {
        return this.nomEnfermedad;
    }
    
    public void setNomEnfermedad(String nomEnfermedad) {
        this.nomEnfermedad = nomEnfermedad;
    }
    public Set<PerAlumno> getPerAlumnos() {
        return this.perAlumnos;
    }
    
    public void setPerAlumnos(Set<PerAlumno> perAlumnos) {
        this.perAlumnos = perAlumnos;
    }




}


