package com.pojos;
// Generated Oct 25, 2019 6:11:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoMatricula generated by hbm2java
 */
public class EstadoMatricula  implements java.io.Serializable {


     private int idEstadoMatricula;
     private String nomEstadoMatricula;
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public EstadoMatricula() {
    }

	
    public EstadoMatricula(int idEstadoMatricula) {
        this.idEstadoMatricula = idEstadoMatricula;
    }
    public EstadoMatricula(int idEstadoMatricula, String nomEstadoMatricula, Set<Matricula> matriculas) {
       this.idEstadoMatricula = idEstadoMatricula;
       this.nomEstadoMatricula = nomEstadoMatricula;
       this.matriculas = matriculas;
    }
   
    public int getIdEstadoMatricula() {
        return this.idEstadoMatricula;
    }
    
    public void setIdEstadoMatricula(int idEstadoMatricula) {
        this.idEstadoMatricula = idEstadoMatricula;
    }
    public String getNomEstadoMatricula() {
        return this.nomEstadoMatricula;
    }
    
    public void setNomEstadoMatricula(String nomEstadoMatricula) {
        this.nomEstadoMatricula = nomEstadoMatricula;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }




}


