package com.pojos;
// Generated Sep 20, 2019 1:20:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoAula generated by hbm2java
 */
public class EstadoAula  implements java.io.Serializable {


     private int idEstadoAula;
     private String nomEstadoAula;
     private Set<Aula> aulas = new HashSet<Aula>(0);

    public EstadoAula() {
    }

	
    public EstadoAula(int idEstadoAula) {
        this.idEstadoAula = idEstadoAula;
    }
    public EstadoAula(int idEstadoAula, String nomEstadoAula, Set<Aula> aulas) {
       this.idEstadoAula = idEstadoAula;
       this.nomEstadoAula = nomEstadoAula;
       this.aulas = aulas;
    }
   
    public int getIdEstadoAula() {
        return this.idEstadoAula;
    }
    
    public void setIdEstadoAula(int idEstadoAula) {
        this.idEstadoAula = idEstadoAula;
    }
    public String getNomEstadoAula() {
        return this.nomEstadoAula;
    }
    
    public void setNomEstadoAula(String nomEstadoAula) {
        this.nomEstadoAula = nomEstadoAula;
    }
    public Set<Aula> getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Set<Aula> aulas) {
        this.aulas = aulas;
    }




}


