package com.pojos;
// Generated Sep 22, 2019 11:27:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoAlumno generated by hbm2java
 */
public class EstadoAlumno  implements java.io.Serializable {


     private int idEstadoAlumno;
     private String nomEstadoAlumno;
     private Set<PerAlumno> perAlumnos = new HashSet<PerAlumno>(0);

    public EstadoAlumno() {
    }

	
    public EstadoAlumno(int idEstadoAlumno) {
        this.idEstadoAlumno = idEstadoAlumno;
    }
    public EstadoAlumno(int idEstadoAlumno, String nomEstadoAlumno, Set<PerAlumno> perAlumnos) {
       this.idEstadoAlumno = idEstadoAlumno;
       this.nomEstadoAlumno = nomEstadoAlumno;
       this.perAlumnos = perAlumnos;
    }
   
    public int getIdEstadoAlumno() {
        return this.idEstadoAlumno;
    }
    
    public void setIdEstadoAlumno(int idEstadoAlumno) {
        this.idEstadoAlumno = idEstadoAlumno;
    }
    public String getNomEstadoAlumno() {
        return this.nomEstadoAlumno;
    }
    
    public void setNomEstadoAlumno(String nomEstadoAlumno) {
        this.nomEstadoAlumno = nomEstadoAlumno;
    }
    public Set<PerAlumno> getPerAlumnos() {
        return this.perAlumnos;
    }
    
    public void setPerAlumnos(Set<PerAlumno> perAlumnos) {
        this.perAlumnos = perAlumnos;
    }




}


