package com.pojos;
// Generated Sep 19, 2019 6:21:09 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoCivil generated by hbm2java
 */
public class EstadoCivil  implements java.io.Serializable {


     private int idEstadoCivil;
     private String nomEstadoCivil;
     private Set<PerApoderado> perApoderados = new HashSet<PerApoderado>(0);

    public EstadoCivil() {
    }

	
    public EstadoCivil(int idEstadoCivil) {
        this.idEstadoCivil = idEstadoCivil;
    }
    public EstadoCivil(int idEstadoCivil, String nomEstadoCivil, Set<PerApoderado> perApoderados) {
       this.idEstadoCivil = idEstadoCivil;
       this.nomEstadoCivil = nomEstadoCivil;
       this.perApoderados = perApoderados;
    }
   
    public int getIdEstadoCivil() {
        return this.idEstadoCivil;
    }
    
    public void setIdEstadoCivil(int idEstadoCivil) {
        this.idEstadoCivil = idEstadoCivil;
    }
    public String getNomEstadoCivil() {
        return this.nomEstadoCivil;
    }
    
    public void setNomEstadoCivil(String nomEstadoCivil) {
        this.nomEstadoCivil = nomEstadoCivil;
    }
    public Set<PerApoderado> getPerApoderados() {
        return this.perApoderados;
    }
    
    public void setPerApoderados(Set<PerApoderado> perApoderados) {
        this.perApoderados = perApoderados;
    }




}


