package com.pojos;
// Generated Sep 28, 2019 5:52:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoUsuario generated by hbm2java
 */
public class EstadoUsuario  implements java.io.Serializable {


     private int idEstadoUsuario;
     private String nomEstadoUsuario;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public EstadoUsuario() {
    }

	
    public EstadoUsuario(int idEstadoUsuario) {
        this.idEstadoUsuario = idEstadoUsuario;
    }
    public EstadoUsuario(int idEstadoUsuario, String nomEstadoUsuario, Set<Usuario> usuarios) {
       this.idEstadoUsuario = idEstadoUsuario;
       this.nomEstadoUsuario = nomEstadoUsuario;
       this.usuarios = usuarios;
    }
   
    public int getIdEstadoUsuario() {
        return this.idEstadoUsuario;
    }
    
    public void setIdEstadoUsuario(int idEstadoUsuario) {
        this.idEstadoUsuario = idEstadoUsuario;
    }
    public String getNomEstadoUsuario() {
        return this.nomEstadoUsuario;
    }
    
    public void setNomEstadoUsuario(String nomEstadoUsuario) {
        this.nomEstadoUsuario = nomEstadoUsuario;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


