package com.pojos;
// Generated Oct 2, 2019 9:32:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GradoInstruccion generated by hbm2java
 */
public class GradoInstruccion  implements java.io.Serializable {


     private int idGradoInstruccion;
     private String nomGradoInstruccion;
     private Set<PerFamiliar> perFamiliars = new HashSet<PerFamiliar>(0);

    public GradoInstruccion() {
    }

	
    public GradoInstruccion(int idGradoInstruccion) {
        this.idGradoInstruccion = idGradoInstruccion;
    }
    public GradoInstruccion(int idGradoInstruccion, String nomGradoInstruccion, Set<PerFamiliar> perFamiliars) {
       this.idGradoInstruccion = idGradoInstruccion;
       this.nomGradoInstruccion = nomGradoInstruccion;
       this.perFamiliars = perFamiliars;
    }
   
    public int getIdGradoInstruccion() {
        return this.idGradoInstruccion;
    }
    
    public void setIdGradoInstruccion(int idGradoInstruccion) {
        this.idGradoInstruccion = idGradoInstruccion;
    }
    public String getNomGradoInstruccion() {
        return this.nomGradoInstruccion;
    }
    
    public void setNomGradoInstruccion(String nomGradoInstruccion) {
        this.nomGradoInstruccion = nomGradoInstruccion;
    }
    public Set<PerFamiliar> getPerFamiliars() {
        return this.perFamiliars;
    }
    
    public void setPerFamiliars(Set<PerFamiliar> perFamiliars) {
        this.perFamiliars = perFamiliars;
    }




}


