package com.pojos;
// Generated Oct 25, 2019 6:11:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private int idMatricula;
     private EstadoMatricula estadoMatricula;
     private PerAlumno perAlumno;
     private PeriodoAnual periodoAnual;
     private String codigoMatricula;
     private Date fecRealizada;
     private Set<HistorialMatricula> historialMatriculas = new HashSet<HistorialMatricula>(0);

    public Matricula() {
    }

	
    public Matricula(int idMatricula, EstadoMatricula estadoMatricula, PerAlumno perAlumno, PeriodoAnual periodoAnual, String codigoMatricula, Date fecRealizada) {
        this.idMatricula = idMatricula;
        this.estadoMatricula = estadoMatricula;
        this.perAlumno = perAlumno;
        this.periodoAnual = periodoAnual;
        this.codigoMatricula = codigoMatricula;
        this.fecRealizada = fecRealizada;
    }
    public Matricula(int idMatricula, EstadoMatricula estadoMatricula, PerAlumno perAlumno, PeriodoAnual periodoAnual, String codigoMatricula, Date fecRealizada, Set<HistorialMatricula> historialMatriculas) {
       this.idMatricula = idMatricula;
       this.estadoMatricula = estadoMatricula;
       this.perAlumno = perAlumno;
       this.periodoAnual = periodoAnual;
       this.codigoMatricula = codigoMatricula;
       this.fecRealizada = fecRealizada;
       this.historialMatriculas = historialMatriculas;
    }
   
    public int getIdMatricula() {
        return this.idMatricula;
    }
    
    public void setIdMatricula(int idMatricula) {
        this.idMatricula = idMatricula;
    }
    public EstadoMatricula getEstadoMatricula() {
        return this.estadoMatricula;
    }
    
    public void setEstadoMatricula(EstadoMatricula estadoMatricula) {
        this.estadoMatricula = estadoMatricula;
    }
    public PerAlumno getPerAlumno() {
        return this.perAlumno;
    }
    
    public void setPerAlumno(PerAlumno perAlumno) {
        this.perAlumno = perAlumno;
    }
    public PeriodoAnual getPeriodoAnual() {
        return this.periodoAnual;
    }
    
    public void setPeriodoAnual(PeriodoAnual periodoAnual) {
        this.periodoAnual = periodoAnual;
    }
    public String getCodigoMatricula() {
        return this.codigoMatricula;
    }
    
    public void setCodigoMatricula(String codigoMatricula) {
        this.codigoMatricula = codigoMatricula;
    }
    public Date getFecRealizada() {
        return this.fecRealizada;
    }
    
    public void setFecRealizada(Date fecRealizada) {
        this.fecRealizada = fecRealizada;
    }
    public Set<HistorialMatricula> getHistorialMatriculas() {
        return this.historialMatriculas;
    }
    
    public void setHistorialMatriculas(Set<HistorialMatricula> historialMatriculas) {
        this.historialMatriculas = historialMatriculas;
    }




}


