package com.pojos;
// Generated Sep 28, 2019 5:52:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private int idMatricula;
     private EstadoMatricula estadoMatricula;
     private PerAlumno perAlumno;
     private PerTrabajador perTrabajador;
     private PeriodoAnual periodoAnual;
     private String codigoMatricula;
     private Date fecRealizada;
     private Date fecModificacion;

    public Matricula() {
    }

	
    public Matricula(int idMatricula, EstadoMatricula estadoMatricula, PerAlumno perAlumno, PerTrabajador perTrabajador, PeriodoAnual periodoAnual, String codigoMatricula, Date fecRealizada) {
        this.idMatricula = idMatricula;
        this.estadoMatricula = estadoMatricula;
        this.perAlumno = perAlumno;
        this.perTrabajador = perTrabajador;
        this.periodoAnual = periodoAnual;
        this.codigoMatricula = codigoMatricula;
        this.fecRealizada = fecRealizada;
    }
    public Matricula(int idMatricula, EstadoMatricula estadoMatricula, PerAlumno perAlumno, PerTrabajador perTrabajador, PeriodoAnual periodoAnual, String codigoMatricula, Date fecRealizada, Date fecModificacion) {
       this.idMatricula = idMatricula;
       this.estadoMatricula = estadoMatricula;
       this.perAlumno = perAlumno;
       this.perTrabajador = perTrabajador;
       this.periodoAnual = periodoAnual;
       this.codigoMatricula = codigoMatricula;
       this.fecRealizada = fecRealizada;
       this.fecModificacion = fecModificacion;
    }
   
    public int getIdMatricula() {
        return this.idMatricula;
    }
    
    public void setIdMatricula(int idMatricula) {
        this.idMatricula = idMatricula;
    }
    public EstadoMatricula getEstadoMatricula() {
        return this.estadoMatricula;
    }
    
    public void setEstadoMatricula(EstadoMatricula estadoMatricula) {
        this.estadoMatricula = estadoMatricula;
    }
    public PerAlumno getPerAlumno() {
        return this.perAlumno;
    }
    
    public void setPerAlumno(PerAlumno perAlumno) {
        this.perAlumno = perAlumno;
    }
    public PerTrabajador getPerTrabajador() {
        return this.perTrabajador;
    }
    
    public void setPerTrabajador(PerTrabajador perTrabajador) {
        this.perTrabajador = perTrabajador;
    }
    public PeriodoAnual getPeriodoAnual() {
        return this.periodoAnual;
    }
    
    public void setPeriodoAnual(PeriodoAnual periodoAnual) {
        this.periodoAnual = periodoAnual;
    }
    public String getCodigoMatricula() {
        return this.codigoMatricula;
    }
    
    public void setCodigoMatricula(String codigoMatricula) {
        this.codigoMatricula = codigoMatricula;
    }
    public Date getFecRealizada() {
        return this.fecRealizada;
    }
    
    public void setFecRealizada(Date fecRealizada) {
        this.fecRealizada = fecRealizada;
    }
    public Date getFecModificacion() {
        return this.fecModificacion;
    }
    
    public void setFecModificacion(Date fecModificacion) {
        this.fecModificacion = fecModificacion;
    }




}


