package com.pojos;
// Generated Sep 22, 2019 11:27:50 PM by Hibernate Tools 4.3.1



/**
 * MultiRole generated by hbm2java
 */
public class MultiRole  implements java.io.Serializable {


     private int idMultiRole;
     private TipoUsuario tipoUsuario;
     private Usuario usuario;

    public MultiRole() {
    }

    public MultiRole(int idMultiRole, TipoUsuario tipoUsuario, Usuario usuario) {
       this.idMultiRole = idMultiRole;
       this.tipoUsuario = tipoUsuario;
       this.usuario = usuario;
    }
   
    public int getIdMultiRole() {
        return this.idMultiRole;
    }
    
    public void setIdMultiRole(int idMultiRole) {
        this.idMultiRole = idMultiRole;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


