package com.pojos;
// Generated Sep 19, 2019 6:21:09 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PerApoderado generated by hbm2java
 */
public class PerApoderado  implements java.io.Serializable {


     private int idPerApoderado;
     private EstadoCivil estadoCivil;
     private Persona persona;
     private TipoApoderado tipoApoderado;
     private boolean flgCopiaDniApo;
     private String gradoInstruccion;
     private String ocupacion;
     private String centroLabores;
     private String telefonoEmergencia;
     private Set<VinculoFamiliar> vinculoFamiliars = new HashSet<VinculoFamiliar>(0);

    public PerApoderado() {
    }

	
    public PerApoderado(int idPerApoderado, EstadoCivil estadoCivil, Persona persona, TipoApoderado tipoApoderado, boolean flgCopiaDniApo, String telefonoEmergencia) {
        this.idPerApoderado = idPerApoderado;
        this.estadoCivil = estadoCivil;
        this.persona = persona;
        this.tipoApoderado = tipoApoderado;
        this.flgCopiaDniApo = flgCopiaDniApo;
        this.telefonoEmergencia = telefonoEmergencia;
    }
    public PerApoderado(int idPerApoderado, EstadoCivil estadoCivil, Persona persona, TipoApoderado tipoApoderado, boolean flgCopiaDniApo, String gradoInstruccion, String ocupacion, String centroLabores, String telefonoEmergencia, Set<VinculoFamiliar> vinculoFamiliars) {
       this.idPerApoderado = idPerApoderado;
       this.estadoCivil = estadoCivil;
       this.persona = persona;
       this.tipoApoderado = tipoApoderado;
       this.flgCopiaDniApo = flgCopiaDniApo;
       this.gradoInstruccion = gradoInstruccion;
       this.ocupacion = ocupacion;
       this.centroLabores = centroLabores;
       this.telefonoEmergencia = telefonoEmergencia;
       this.vinculoFamiliars = vinculoFamiliars;
    }
   
    public int getIdPerApoderado() {
        return this.idPerApoderado;
    }
    
    public void setIdPerApoderado(int idPerApoderado) {
        this.idPerApoderado = idPerApoderado;
    }
    public EstadoCivil getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(EstadoCivil estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public TipoApoderado getTipoApoderado() {
        return this.tipoApoderado;
    }
    
    public void setTipoApoderado(TipoApoderado tipoApoderado) {
        this.tipoApoderado = tipoApoderado;
    }
    public boolean isFlgCopiaDniApo() {
        return this.flgCopiaDniApo;
    }
    
    public void setFlgCopiaDniApo(boolean flgCopiaDniApo) {
        this.flgCopiaDniApo = flgCopiaDniApo;
    }
    public String getGradoInstruccion() {
        return this.gradoInstruccion;
    }
    
    public void setGradoInstruccion(String gradoInstruccion) {
        this.gradoInstruccion = gradoInstruccion;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getCentroLabores() {
        return this.centroLabores;
    }
    
    public void setCentroLabores(String centroLabores) {
        this.centroLabores = centroLabores;
    }
    public String getTelefonoEmergencia() {
        return this.telefonoEmergencia;
    }
    
    public void setTelefonoEmergencia(String telefonoEmergencia) {
        this.telefonoEmergencia = telefonoEmergencia;
    }
    public Set<VinculoFamiliar> getVinculoFamiliars() {
        return this.vinculoFamiliars;
    }
    
    public void setVinculoFamiliars(Set<VinculoFamiliar> vinculoFamiliars) {
        this.vinculoFamiliars = vinculoFamiliars;
    }




}


