package com.pojos;
// Generated Oct 2, 2019 9:32:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PerAlumno generated by hbm2java
 */
public class PerAlumno  implements java.io.Serializable {


     private int idPerAlumno;
     private Persona persona;
     private TipoAlumno tipoAlumno;
     private int codigoAlumno;
     private String nombreIeAnterior;
     private String refNivel;
     private char refGradoAnterior;
     private char refSeccion;
     private Double refPonderadoAnterior;
     private Boolean flgTercioSuperior;
     private String grupoSanguineo;
     private String lenguaMaterna;
     private String segundaLengua;
     private int nroHermanos;
     private boolean flgCopiaDni;
     private boolean flgViveConPadres;
     private boolean flgFotoAlumno;
     private Set<Religion> religions = new HashSet<Religion>(0);
     private Set<Enfermedad> enfermedads = new HashSet<Enfermedad>(0);
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);
     private Set<VinculoFamiliar> vinculoFamiliars = new HashSet<VinculoFamiliar>(0);
     private Set<Alergia> alergias = new HashSet<Alergia>(0);
     private Set<Discapacidad> discapacidads = new HashSet<Discapacidad>(0);

    public PerAlumno() {
    }

	
    public PerAlumno(int idPerAlumno, Persona persona, TipoAlumno tipoAlumno, int codigoAlumno, String refNivel, char refGradoAnterior, char refSeccion, String grupoSanguineo, String lenguaMaterna, int nroHermanos, boolean flgCopiaDni, boolean flgViveConPadres, boolean flgFotoAlumno) {
        this.idPerAlumno = idPerAlumno;
        this.persona = persona;
        this.tipoAlumno = tipoAlumno;
        this.codigoAlumno = codigoAlumno;
        this.refNivel = refNivel;
        this.refGradoAnterior = refGradoAnterior;
        this.refSeccion = refSeccion;
        this.grupoSanguineo = grupoSanguineo;
        this.lenguaMaterna = lenguaMaterna;
        this.nroHermanos = nroHermanos;
        this.flgCopiaDni = flgCopiaDni;
        this.flgViveConPadres = flgViveConPadres;
        this.flgFotoAlumno = flgFotoAlumno;
    }
    public PerAlumno(int idPerAlumno, Persona persona, TipoAlumno tipoAlumno, int codigoAlumno, String nombreIeAnterior, String refNivel, char refGradoAnterior, char refSeccion, Double refPonderadoAnterior, Boolean flgTercioSuperior, String grupoSanguineo, String lenguaMaterna, String segundaLengua, int nroHermanos, boolean flgCopiaDni, boolean flgViveConPadres, boolean flgFotoAlumno, Set<Religion> religions, Set<Enfermedad> enfermedads, Set<Matricula> matriculas, Set<VinculoFamiliar> vinculoFamiliars, Set<Alergia> alergias, Set<Discapacidad> discapacidads) {
       this.idPerAlumno = idPerAlumno;
       this.persona = persona;
       this.tipoAlumno = tipoAlumno;
       this.codigoAlumno = codigoAlumno;
       this.nombreIeAnterior = nombreIeAnterior;
       this.refNivel = refNivel;
       this.refGradoAnterior = refGradoAnterior;
       this.refSeccion = refSeccion;
       this.refPonderadoAnterior = refPonderadoAnterior;
       this.flgTercioSuperior = flgTercioSuperior;
       this.grupoSanguineo = grupoSanguineo;
       this.lenguaMaterna = lenguaMaterna;
       this.segundaLengua = segundaLengua;
       this.nroHermanos = nroHermanos;
       this.flgCopiaDni = flgCopiaDni;
       this.flgViveConPadres = flgViveConPadres;
       this.flgFotoAlumno = flgFotoAlumno;
       this.religions = religions;
       this.enfermedads = enfermedads;
       this.matriculas = matriculas;
       this.vinculoFamiliars = vinculoFamiliars;
       this.alergias = alergias;
       this.discapacidads = discapacidads;
    }
   
    public int getIdPerAlumno() {
        return this.idPerAlumno;
    }
    
    public void setIdPerAlumno(int idPerAlumno) {
        this.idPerAlumno = idPerAlumno;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public TipoAlumno getTipoAlumno() {
        return this.tipoAlumno;
    }
    
    public void setTipoAlumno(TipoAlumno tipoAlumno) {
        this.tipoAlumno = tipoAlumno;
    }
    public int getCodigoAlumno() {
        return this.codigoAlumno;
    }
    
    public void setCodigoAlumno(int codigoAlumno) {
        this.codigoAlumno = codigoAlumno;
    }
    public String getNombreIeAnterior() {
        return this.nombreIeAnterior;
    }
    
    public void setNombreIeAnterior(String nombreIeAnterior) {
        this.nombreIeAnterior = nombreIeAnterior;
    }
    public String getRefNivel() {
        return this.refNivel;
    }
    
    public void setRefNivel(String refNivel) {
        this.refNivel = refNivel;
    }
    public char getRefGradoAnterior() {
        return this.refGradoAnterior;
    }
    
    public void setRefGradoAnterior(char refGradoAnterior) {
        this.refGradoAnterior = refGradoAnterior;
    }
    public char getRefSeccion() {
        return this.refSeccion;
    }
    
    public void setRefSeccion(char refSeccion) {
        this.refSeccion = refSeccion;
    }
    public Double getRefPonderadoAnterior() {
        return this.refPonderadoAnterior;
    }
    
    public void setRefPonderadoAnterior(Double refPonderadoAnterior) {
        this.refPonderadoAnterior = refPonderadoAnterior;
    }
    public Boolean getFlgTercioSuperior() {
        return this.flgTercioSuperior;
    }
    
    public void setFlgTercioSuperior(Boolean flgTercioSuperior) {
        this.flgTercioSuperior = flgTercioSuperior;
    }
    public String getGrupoSanguineo() {
        return this.grupoSanguineo;
    }
    
    public void setGrupoSanguineo(String grupoSanguineo) {
        this.grupoSanguineo = grupoSanguineo;
    }
    public String getLenguaMaterna() {
        return this.lenguaMaterna;
    }
    
    public void setLenguaMaterna(String lenguaMaterna) {
        this.lenguaMaterna = lenguaMaterna;
    }
    public String getSegundaLengua() {
        return this.segundaLengua;
    }
    
    public void setSegundaLengua(String segundaLengua) {
        this.segundaLengua = segundaLengua;
    }
    public int getNroHermanos() {
        return this.nroHermanos;
    }
    
    public void setNroHermanos(int nroHermanos) {
        this.nroHermanos = nroHermanos;
    }
    public boolean isFlgCopiaDni() {
        return this.flgCopiaDni;
    }
    
    public void setFlgCopiaDni(boolean flgCopiaDni) {
        this.flgCopiaDni = flgCopiaDni;
    }
    public boolean isFlgViveConPadres() {
        return this.flgViveConPadres;
    }
    
    public void setFlgViveConPadres(boolean flgViveConPadres) {
        this.flgViveConPadres = flgViveConPadres;
    }
    public boolean isFlgFotoAlumno() {
        return this.flgFotoAlumno;
    }
    
    public void setFlgFotoAlumno(boolean flgFotoAlumno) {
        this.flgFotoAlumno = flgFotoAlumno;
    }
    public Set<Religion> getReligions() {
        return this.religions;
    }
    
    public void setReligions(Set<Religion> religions) {
        this.religions = religions;
    }
    public Set<Enfermedad> getEnfermedads() {
        return this.enfermedads;
    }
    
    public void setEnfermedads(Set<Enfermedad> enfermedads) {
        this.enfermedads = enfermedads;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }
    public Set<VinculoFamiliar> getVinculoFamiliars() {
        return this.vinculoFamiliars;
    }
    
    public void setVinculoFamiliars(Set<VinculoFamiliar> vinculoFamiliars) {
        this.vinculoFamiliars = vinculoFamiliars;
    }
    public Set<Alergia> getAlergias() {
        return this.alergias;
    }
    
    public void setAlergias(Set<Alergia> alergias) {
        this.alergias = alergias;
    }
    public Set<Discapacidad> getDiscapacidads() {
        return this.discapacidads;
    }
    
    public void setDiscapacidads(Set<Discapacidad> discapacidads) {
        this.discapacidads = discapacidads;
    }




}


