package com.pojos;
// Generated Oct 28, 2019 1:09:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PerAlumno generated by hbm2java
 */
public class PerAlumno  implements java.io.Serializable {


     private int idPerAlumno;
     private Persona persona;
     private TipoAlumno tipoAlumno;
     private int codigoAlumno;
     private String nombreIeAnterior;
     private String refNivel;
     private char refGradoAnterior;
     private char refSeccion;
     private double refPonderadoAnterior;
     private Boolean flgOrdenMerito;
     private String grupoSanguineo;
     private String lenguaMaterna;
     private String segundaLengua;
     private int nroHermanos;
     private boolean flgCopiaDni;
     private boolean flgViveConPadres;
     private Set<VinculoFamiliar> vinculoFamiliars = new HashSet<VinculoFamiliar>(0);
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public PerAlumno() {
    }

	
    public PerAlumno(int idPerAlumno, Persona persona, TipoAlumno tipoAlumno, int codigoAlumno, String nombreIeAnterior, String refNivel, char refGradoAnterior, char refSeccion, double refPonderadoAnterior, String grupoSanguineo, String lenguaMaterna, int nroHermanos, boolean flgCopiaDni, boolean flgViveConPadres) {
        this.idPerAlumno = idPerAlumno;
        this.persona = persona;
        this.tipoAlumno = tipoAlumno;
        this.codigoAlumno = codigoAlumno;
        this.nombreIeAnterior = nombreIeAnterior;
        this.refNivel = refNivel;
        this.refGradoAnterior = refGradoAnterior;
        this.refSeccion = refSeccion;
        this.refPonderadoAnterior = refPonderadoAnterior;
        this.grupoSanguineo = grupoSanguineo;
        this.lenguaMaterna = lenguaMaterna;
        this.nroHermanos = nroHermanos;
        this.flgCopiaDni = flgCopiaDni;
        this.flgViveConPadres = flgViveConPadres;
    }
    public PerAlumno(int idPerAlumno, Persona persona, TipoAlumno tipoAlumno, int codigoAlumno, String nombreIeAnterior, String refNivel, char refGradoAnterior, char refSeccion, double refPonderadoAnterior, Boolean flgOrdenMerito, String grupoSanguineo, String lenguaMaterna, String segundaLengua, int nroHermanos, boolean flgCopiaDni, boolean flgViveConPadres, Set<VinculoFamiliar> vinculoFamiliars, Set<Matricula> matriculas) {
       this.idPerAlumno = idPerAlumno;
       this.persona = persona;
       this.tipoAlumno = tipoAlumno;
       this.codigoAlumno = codigoAlumno;
       this.nombreIeAnterior = nombreIeAnterior;
       this.refNivel = refNivel;
       this.refGradoAnterior = refGradoAnterior;
       this.refSeccion = refSeccion;
       this.refPonderadoAnterior = refPonderadoAnterior;
       this.flgOrdenMerito = flgOrdenMerito;
       this.grupoSanguineo = grupoSanguineo;
       this.lenguaMaterna = lenguaMaterna;
       this.segundaLengua = segundaLengua;
       this.nroHermanos = nroHermanos;
       this.flgCopiaDni = flgCopiaDni;
       this.flgViveConPadres = flgViveConPadres;
       this.vinculoFamiliars = vinculoFamiliars;
       this.matriculas = matriculas;
    }
   
    public int getIdPerAlumno() {
        return this.idPerAlumno;
    }
    
    public void setIdPerAlumno(int idPerAlumno) {
        this.idPerAlumno = idPerAlumno;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public TipoAlumno getTipoAlumno() {
        return this.tipoAlumno;
    }
    
    public void setTipoAlumno(TipoAlumno tipoAlumno) {
        this.tipoAlumno = tipoAlumno;
    }
    public int getCodigoAlumno() {
        return this.codigoAlumno;
    }
    
    public void setCodigoAlumno(int codigoAlumno) {
        this.codigoAlumno = codigoAlumno;
    }
    public String getNombreIeAnterior() {
        return this.nombreIeAnterior;
    }
    
    public void setNombreIeAnterior(String nombreIeAnterior) {
        this.nombreIeAnterior = nombreIeAnterior;
    }
    public String getRefNivel() {
        return this.refNivel;
    }
    
    public void setRefNivel(String refNivel) {
        this.refNivel = refNivel;
    }
    public char getRefGradoAnterior() {
        return this.refGradoAnterior;
    }
    
    public void setRefGradoAnterior(char refGradoAnterior) {
        this.refGradoAnterior = refGradoAnterior;
    }
    public char getRefSeccion() {
        return this.refSeccion;
    }
    
    public void setRefSeccion(char refSeccion) {
        this.refSeccion = refSeccion;
    }
    public double getRefPonderadoAnterior() {
        return this.refPonderadoAnterior;
    }
    
    public void setRefPonderadoAnterior(double refPonderadoAnterior) {
        this.refPonderadoAnterior = refPonderadoAnterior;
    }
    public Boolean getFlgOrdenMerito() {
        return this.flgOrdenMerito;
    }
    
    public void setFlgOrdenMerito(Boolean flgOrdenMerito) {
        this.flgOrdenMerito = flgOrdenMerito;
    }
    public String getGrupoSanguineo() {
        return this.grupoSanguineo;
    }
    
    public void setGrupoSanguineo(String grupoSanguineo) {
        this.grupoSanguineo = grupoSanguineo;
    }
    public String getLenguaMaterna() {
        return this.lenguaMaterna;
    }
    
    public void setLenguaMaterna(String lenguaMaterna) {
        this.lenguaMaterna = lenguaMaterna;
    }
    public String getSegundaLengua() {
        return this.segundaLengua;
    }
    
    public void setSegundaLengua(String segundaLengua) {
        this.segundaLengua = segundaLengua;
    }
    public int getNroHermanos() {
        return this.nroHermanos;
    }
    
    public void setNroHermanos(int nroHermanos) {
        this.nroHermanos = nroHermanos;
    }
    public boolean isFlgCopiaDni() {
        return this.flgCopiaDni;
    }
    
    public void setFlgCopiaDni(boolean flgCopiaDni) {
        this.flgCopiaDni = flgCopiaDni;
    }
    public boolean isFlgViveConPadres() {
        return this.flgViveConPadres;
    }
    
    public void setFlgViveConPadres(boolean flgViveConPadres) {
        this.flgViveConPadres = flgViveConPadres;
    }
    public Set<VinculoFamiliar> getVinculoFamiliars() {
        return this.vinculoFamiliars;
    }
    
    public void setVinculoFamiliars(Set<VinculoFamiliar> vinculoFamiliars) {
        this.vinculoFamiliars = vinculoFamiliars;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }




}


