package com.pojos;
// Generated Sep 28, 2019 5:52:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PerFamiliar generated by hbm2java
 */
public class PerFamiliar  implements java.io.Serializable {


     private int idPerFamiliar;
     private EstadoCivil estadoCivil;
     private GradoInstruccion gradoInstruccion;
     private Persona persona;
     private TipoFamiliar tipoFamiliar;
     private boolean flgCopiaDniApo;
     private String dscrpOcupacion;
     private String telefonoEmergencia;
     private Set<CentroLabores> centroLaboreses = new HashSet<CentroLabores>(0);
     private Set<VinculoFamiliar> vinculoFamiliars = new HashSet<VinculoFamiliar>(0);

    public PerFamiliar() {
    }

	
    public PerFamiliar(int idPerFamiliar, EstadoCivil estadoCivil, GradoInstruccion gradoInstruccion, Persona persona, TipoFamiliar tipoFamiliar, boolean flgCopiaDniApo, String telefonoEmergencia) {
        this.idPerFamiliar = idPerFamiliar;
        this.estadoCivil = estadoCivil;
        this.gradoInstruccion = gradoInstruccion;
        this.persona = persona;
        this.tipoFamiliar = tipoFamiliar;
        this.flgCopiaDniApo = flgCopiaDniApo;
        this.telefonoEmergencia = telefonoEmergencia;
    }
    public PerFamiliar(int idPerFamiliar, EstadoCivil estadoCivil, GradoInstruccion gradoInstruccion, Persona persona, TipoFamiliar tipoFamiliar, boolean flgCopiaDniApo, String dscrpOcupacion, String telefonoEmergencia, Set<CentroLabores> centroLaboreses, Set<VinculoFamiliar> vinculoFamiliars) {
       this.idPerFamiliar = idPerFamiliar;
       this.estadoCivil = estadoCivil;
       this.gradoInstruccion = gradoInstruccion;
       this.persona = persona;
       this.tipoFamiliar = tipoFamiliar;
       this.flgCopiaDniApo = flgCopiaDniApo;
       this.dscrpOcupacion = dscrpOcupacion;
       this.telefonoEmergencia = telefonoEmergencia;
       this.centroLaboreses = centroLaboreses;
       this.vinculoFamiliars = vinculoFamiliars;
    }
   
    public int getIdPerFamiliar() {
        return this.idPerFamiliar;
    }
    
    public void setIdPerFamiliar(int idPerFamiliar) {
        this.idPerFamiliar = idPerFamiliar;
    }
    public EstadoCivil getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(EstadoCivil estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public GradoInstruccion getGradoInstruccion() {
        return this.gradoInstruccion;
    }
    
    public void setGradoInstruccion(GradoInstruccion gradoInstruccion) {
        this.gradoInstruccion = gradoInstruccion;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public TipoFamiliar getTipoFamiliar() {
        return this.tipoFamiliar;
    }
    
    public void setTipoFamiliar(TipoFamiliar tipoFamiliar) {
        this.tipoFamiliar = tipoFamiliar;
    }
    public boolean isFlgCopiaDniApo() {
        return this.flgCopiaDniApo;
    }
    
    public void setFlgCopiaDniApo(boolean flgCopiaDniApo) {
        this.flgCopiaDniApo = flgCopiaDniApo;
    }
    public String getDscrpOcupacion() {
        return this.dscrpOcupacion;
    }
    
    public void setDscrpOcupacion(String dscrpOcupacion) {
        this.dscrpOcupacion = dscrpOcupacion;
    }
    public String getTelefonoEmergencia() {
        return this.telefonoEmergencia;
    }
    
    public void setTelefonoEmergencia(String telefonoEmergencia) {
        this.telefonoEmergencia = telefonoEmergencia;
    }
    public Set<CentroLabores> getCentroLaboreses() {
        return this.centroLaboreses;
    }
    
    public void setCentroLaboreses(Set<CentroLabores> centroLaboreses) {
        this.centroLaboreses = centroLaboreses;
    }
    public Set<VinculoFamiliar> getVinculoFamiliars() {
        return this.vinculoFamiliars;
    }
    
    public void setVinculoFamiliars(Set<VinculoFamiliar> vinculoFamiliars) {
        this.vinculoFamiliars = vinculoFamiliars;
    }




}


