package com.pojos;
// Generated Sep 22, 2019 11:27:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PerFamiliar generated by hbm2java
 */
public class PerFamiliar  implements java.io.Serializable {


     private int idPerFamiliar;
     private EstadoCivil estadoCivil;
     private Persona persona;
     private TipoFamiliar tipoFamiliar;
     private boolean flgCopiaDniApo;
     private String gradoInstruccion;
     private String ocupacion;
     private String centroLabores;
     private String telefonoEmergencia;
     private Set<VinculoFamiliar> vinculoFamiliars = new HashSet<VinculoFamiliar>(0);

    public PerFamiliar() {
    }

	
    public PerFamiliar(int idPerFamiliar, EstadoCivil estadoCivil, Persona persona, TipoFamiliar tipoFamiliar, boolean flgCopiaDniApo, String telefonoEmergencia) {
        this.idPerFamiliar = idPerFamiliar;
        this.estadoCivil = estadoCivil;
        this.persona = persona;
        this.tipoFamiliar = tipoFamiliar;
        this.flgCopiaDniApo = flgCopiaDniApo;
        this.telefonoEmergencia = telefonoEmergencia;
    }
    public PerFamiliar(int idPerFamiliar, EstadoCivil estadoCivil, Persona persona, TipoFamiliar tipoFamiliar, boolean flgCopiaDniApo, String gradoInstruccion, String ocupacion, String centroLabores, String telefonoEmergencia, Set<VinculoFamiliar> vinculoFamiliars) {
       this.idPerFamiliar = idPerFamiliar;
       this.estadoCivil = estadoCivil;
       this.persona = persona;
       this.tipoFamiliar = tipoFamiliar;
       this.flgCopiaDniApo = flgCopiaDniApo;
       this.gradoInstruccion = gradoInstruccion;
       this.ocupacion = ocupacion;
       this.centroLabores = centroLabores;
       this.telefonoEmergencia = telefonoEmergencia;
       this.vinculoFamiliars = vinculoFamiliars;
    }
   
    public int getIdPerFamiliar() {
        return this.idPerFamiliar;
    }
    
    public void setIdPerFamiliar(int idPerFamiliar) {
        this.idPerFamiliar = idPerFamiliar;
    }
    public EstadoCivil getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(EstadoCivil estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public TipoFamiliar getTipoFamiliar() {
        return this.tipoFamiliar;
    }
    
    public void setTipoFamiliar(TipoFamiliar tipoFamiliar) {
        this.tipoFamiliar = tipoFamiliar;
    }
    public boolean isFlgCopiaDniApo() {
        return this.flgCopiaDniApo;
    }
    
    public void setFlgCopiaDniApo(boolean flgCopiaDniApo) {
        this.flgCopiaDniApo = flgCopiaDniApo;
    }
    public String getGradoInstruccion() {
        return this.gradoInstruccion;
    }
    
    public void setGradoInstruccion(String gradoInstruccion) {
        this.gradoInstruccion = gradoInstruccion;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getCentroLabores() {
        return this.centroLabores;
    }
    
    public void setCentroLabores(String centroLabores) {
        this.centroLabores = centroLabores;
    }
    public String getTelefonoEmergencia() {
        return this.telefonoEmergencia;
    }
    
    public void setTelefonoEmergencia(String telefonoEmergencia) {
        this.telefonoEmergencia = telefonoEmergencia;
    }
    public Set<VinculoFamiliar> getVinculoFamiliars() {
        return this.vinculoFamiliars;
    }
    
    public void setVinculoFamiliars(Set<VinculoFamiliar> vinculoFamiliars) {
        this.vinculoFamiliars = vinculoFamiliars;
    }




}


