package com.pojos;
// Generated Oct 25, 2019 6:11:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private String primerNombre;
     private String apellidoMaterno;
     private String apellidoPaterno;
     private String numeroDocumento;
     private Date fecNacimiento;
     private char sexo;
     private String telefonoCasa;
     private String telefonoCelular;
     private String direccion;
     private String correo;
     private Set<PerAlumno> perAlumnos = new HashSet<PerAlumno>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<PerTrabajador> perTrabajadors = new HashSet<PerTrabajador>(0);

    public Persona() {
    }

	
    public Persona(int idPersona, String primerNombre, String apellidoMaterno, String apellidoPaterno, String numeroDocumento, Date fecNacimiento, char sexo, String direccion) {
        this.idPersona = idPersona;
        this.primerNombre = primerNombre;
        this.apellidoMaterno = apellidoMaterno;
        this.apellidoPaterno = apellidoPaterno;
        this.numeroDocumento = numeroDocumento;
        this.fecNacimiento = fecNacimiento;
        this.sexo = sexo;
        this.direccion = direccion;
    }
    public Persona(int idPersona, String primerNombre, String apellidoMaterno, String apellidoPaterno, String numeroDocumento, Date fecNacimiento, char sexo, String telefonoCasa, String telefonoCelular, String direccion, String correo, Set<PerAlumno> perAlumnos, Set<Usuario> usuarios, Set<PerTrabajador> perTrabajadors) {
       this.idPersona = idPersona;
       this.primerNombre = primerNombre;
       this.apellidoMaterno = apellidoMaterno;
       this.apellidoPaterno = apellidoPaterno;
       this.numeroDocumento = numeroDocumento;
       this.fecNacimiento = fecNacimiento;
       this.sexo = sexo;
       this.telefonoCasa = telefonoCasa;
       this.telefonoCelular = telefonoCelular;
       this.direccion = direccion;
       this.correo = correo;
       this.perAlumnos = perAlumnos;
       this.usuarios = usuarios;
       this.perTrabajadors = perTrabajadors;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public Date getFecNacimiento() {
        return this.fecNacimiento;
    }
    
    public void setFecNacimiento(Date fecNacimiento) {
        this.fecNacimiento = fecNacimiento;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public String getTelefonoCasa() {
        return this.telefonoCasa;
    }
    
    public void setTelefonoCasa(String telefonoCasa) {
        this.telefonoCasa = telefonoCasa;
    }
    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }
    
    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set<PerAlumno> getPerAlumnos() {
        return this.perAlumnos;
    }
    
    public void setPerAlumnos(Set<PerAlumno> perAlumnos) {
        this.perAlumnos = perAlumnos;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<PerTrabajador> getPerTrabajadors() {
        return this.perTrabajadors;
    }
    
    public void setPerTrabajadors(Set<PerTrabajador> perTrabajadors) {
        this.perTrabajadors = perTrabajadors;
    }




}


