package com.pojos;
// Generated Sep 28, 2019 5:52:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PerTrabajador generated by hbm2java
 */
public class PerTrabajador  implements java.io.Serializable {


     private int idPerTrabajador;
     private Persona persona;
     private int codigoTrabajador;
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public PerTrabajador() {
    }

	
    public PerTrabajador(int idPerTrabajador, Persona persona, int codigoTrabajador) {
        this.idPerTrabajador = idPerTrabajador;
        this.persona = persona;
        this.codigoTrabajador = codigoTrabajador;
    }
    public PerTrabajador(int idPerTrabajador, Persona persona, int codigoTrabajador, Set<Matricula> matriculas) {
       this.idPerTrabajador = idPerTrabajador;
       this.persona = persona;
       this.codigoTrabajador = codigoTrabajador;
       this.matriculas = matriculas;
    }
   
    public int getIdPerTrabajador() {
        return this.idPerTrabajador;
    }
    
    public void setIdPerTrabajador(int idPerTrabajador) {
        this.idPerTrabajador = idPerTrabajador;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public int getCodigoTrabajador() {
        return this.codigoTrabajador;
    }
    
    public void setCodigoTrabajador(int codigoTrabajador) {
        this.codigoTrabajador = codigoTrabajador;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }




}


