package com.pojos;
// Generated Sep 20, 2019 1:20:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Religion generated by hbm2java
 */
public class Religion  implements java.io.Serializable {


     private int idReligion;
     private String nomReligion;
     private Set<PerAlumno> perAlumnos = new HashSet<PerAlumno>(0);

    public Religion() {
    }

	
    public Religion(int idReligion) {
        this.idReligion = idReligion;
    }
    public Religion(int idReligion, String nomReligion, Set<PerAlumno> perAlumnos) {
       this.idReligion = idReligion;
       this.nomReligion = nomReligion;
       this.perAlumnos = perAlumnos;
    }
   
    public int getIdReligion() {
        return this.idReligion;
    }
    
    public void setIdReligion(int idReligion) {
        this.idReligion = idReligion;
    }
    public String getNomReligion() {
        return this.nomReligion;
    }
    
    public void setNomReligion(String nomReligion) {
        this.nomReligion = nomReligion;
    }
    public Set<PerAlumno> getPerAlumnos() {
        return this.perAlumnos;
    }
    
    public void setPerAlumnos(Set<PerAlumno> perAlumnos) {
        this.perAlumnos = perAlumnos;
    }




}


