package com.pojos;
// Generated Oct 25, 2019 6:11:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoAlumno generated by hbm2java
 */
public class TipoAlumno  implements java.io.Serializable {


     private int idTipoAlumno;
     private String nomTipoAlumno;
     private Set<PerAlumno> perAlumnos = new HashSet<PerAlumno>(0);

    public TipoAlumno() {
    }

	
    public TipoAlumno(int idTipoAlumno) {
        this.idTipoAlumno = idTipoAlumno;
    }
    public TipoAlumno(int idTipoAlumno, String nomTipoAlumno, Set<PerAlumno> perAlumnos) {
       this.idTipoAlumno = idTipoAlumno;
       this.nomTipoAlumno = nomTipoAlumno;
       this.perAlumnos = perAlumnos;
    }
   
    public int getIdTipoAlumno() {
        return this.idTipoAlumno;
    }
    
    public void setIdTipoAlumno(int idTipoAlumno) {
        this.idTipoAlumno = idTipoAlumno;
    }
    public String getNomTipoAlumno() {
        return this.nomTipoAlumno;
    }
    
    public void setNomTipoAlumno(String nomTipoAlumno) {
        this.nomTipoAlumno = nomTipoAlumno;
    }
    public Set<PerAlumno> getPerAlumnos() {
        return this.perAlumnos;
    }
    
    public void setPerAlumnos(Set<PerAlumno> perAlumnos) {
        this.perAlumnos = perAlumnos;
    }




}


