package com.pojos;
// Generated Oct 25, 2019 6:11:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Persona persona;
     private String username;
     private String password;
     private Date fecCreacion;

    public Usuario() {
    }

	
    public Usuario(int idUsuario, Persona persona, String username, String password) {
        this.idUsuario = idUsuario;
        this.persona = persona;
        this.username = username;
        this.password = password;
    }
    public Usuario(int idUsuario, Persona persona, String username, String password, Date fecCreacion) {
       this.idUsuario = idUsuario;
       this.persona = persona;
       this.username = username;
       this.password = password;
       this.fecCreacion = fecCreacion;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }




}


