package com.pojos;
// Generated Oct 28, 2019 1:09:51 PM by Hibernate Tools 4.3.1



/**
 * VinculoFamiliarId generated by hbm2java
 */
public class VinculoFamiliarId  implements java.io.Serializable {


     private int fkidPerAlumno;
     private int fkidPerFamiliar;

    public VinculoFamiliarId() {
    }

    public VinculoFamiliarId(int fkidPerAlumno, int fkidPerFamiliar) {
       this.fkidPerAlumno = fkidPerAlumno;
       this.fkidPerFamiliar = fkidPerFamiliar;
    }
   
    public int getFkidPerAlumno() {
        return this.fkidPerAlumno;
    }
    
    public void setFkidPerAlumno(int fkidPerAlumno) {
        this.fkidPerAlumno = fkidPerAlumno;
    }
    public int getFkidPerFamiliar() {
        return this.fkidPerFamiliar;
    }
    
    public void setFkidPerFamiliar(int fkidPerFamiliar) {
        this.fkidPerFamiliar = fkidPerFamiliar;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VinculoFamiliarId) ) return false;
		 VinculoFamiliarId castOther = ( VinculoFamiliarId ) other; 
         
		 return (this.getFkidPerAlumno()==castOther.getFkidPerAlumno())
 && (this.getFkidPerFamiliar()==castOther.getFkidPerFamiliar());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkidPerAlumno();
         result = 37 * result + this.getFkidPerFamiliar();
         return result;
   }   


}


