package com.pojos;
// Generated Sep 19, 2019 6:21:09 AM by Hibernate Tools 4.3.1



/**
 * VinculoFamiliarId generated by hbm2java
 */
public class VinculoFamiliarId  implements java.io.Serializable {


     private int fkidPerAlumno;
     private int fkidPerApoderado;

    public VinculoFamiliarId() {
    }

    public VinculoFamiliarId(int fkidPerAlumno, int fkidPerApoderado) {
       this.fkidPerAlumno = fkidPerAlumno;
       this.fkidPerApoderado = fkidPerApoderado;
    }
   
    public int getFkidPerAlumno() {
        return this.fkidPerAlumno;
    }
    
    public void setFkidPerAlumno(int fkidPerAlumno) {
        this.fkidPerAlumno = fkidPerAlumno;
    }
    public int getFkidPerApoderado() {
        return this.fkidPerApoderado;
    }
    
    public void setFkidPerApoderado(int fkidPerApoderado) {
        this.fkidPerApoderado = fkidPerApoderado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VinculoFamiliarId) ) return false;
		 VinculoFamiliarId castOther = ( VinculoFamiliarId ) other; 
         
		 return (this.getFkidPerAlumno()==castOther.getFkidPerAlumno())
 && (this.getFkidPerApoderado()==castOther.getFkidPerApoderado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkidPerAlumno();
         result = 37 * result + this.getFkidPerApoderado();
         return result;
   }   


}


